"""add Department

Revision ID: 145ce76b544d
Revises: 76d7ae868bef
Create Date: 2024-06-30 01:56:02.163748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145ce76b544d'
down_revision = '76d7ae868bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
