"""rename address

Revision ID: 77662810f8ad
Revises: 00bacb19849b
Create Date: 2024-07-01 14:47:18.303641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77662810f8ad'
down_revision = '00bacb19849b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'location', new_column_name='address')
    # ### end Alembic commands ###
